# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
language: c
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages
    - $HOME/.stack

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

env:
  global:
    secure: "IRtE1XwgzQKlD/fzNrapx8l3dVIC8/0BeQoA3C2qQM7BW2BVs5Z12tX/I1nco3E7J5SwfMWStGJxgghcI1t4uTKg6Q1CQDhNNy+Sr3jX9kd3Evvd3HacE/FiBBtIoiE1tIqd0/duCpJ+EH5d9Gd/Zk+1BWnDTdEdAYZVbc6sEMM="

matrix:
  include:
    - env: BUILD=cabal CABALVER=1.18 GHCVER=7.8.4
      compiler: ": #GHC 7.8.4"
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.18 GHCVER=7.8.4 STACKAGESNAPSHOT=lts-2.22
      compiler: ": #GHC 7.8.4 lts-2.22"
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.2 STACKAGESNAPSHOT=lts-3.21
      compiler: ": #GHC 7.10.2 lts-3.21"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.3
      compiler: ": #GHC 7.10.3"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.3 STACKAGESNAPSHOT=lts-4.0
      compiler: ": #GHC 7.10.3 lts-4.0"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-lts-2.yaml GHCVER=7.8.4
      compiler: ": #STACK LTS2"
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-lts-3.yaml GHCVER=7.10.2
      compiler: ": #STACK LTS3"
      addons: {apt: {packages: [ghc-7.10.2], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-lts-4.yaml  GHCVER=7.10.3
      compiler: ": #STACK LTS4"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-nightly.yaml GHCVER=7.10.3
      compiler: ": #STACK nightly"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-lts-4.yaml
      compiler: ": #stack LTS4 OSX"
      os: osx

before_install:
  - unset CC
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH

install:
  - sh travis-install.sh

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
  - sh travis-script.sh

branches:
  only:
  - master

# EOF
