name: github-samples

ghc-options: -Wall

dependencies:
  - base
  - base-compat
  - github
  - text

library:
  source-dirs: src

executables:
  github-show-user:
    main: ShowUser.hs
    source-dirs: Users
    dependencies:
      - github-samples
  github-list-followers:
    main: ListFollowers.hs
    source-dirs: Users/Followers
    dependencies:
      - github-samples
  github-list-following:
    main: ListFollowing.hs
    source-dirs: Users/Followers
    dependencies:
      - github-samples
  github-delete-team:
    main: DeleteTeam.hs
    source-dirs: Teams
    dependencies:
      - github-samples
  github-edit-team:
    main: EditTeam.hs
    source-dirs: Teams
    dependencies:
      - github-samples
  github-list-team-current:
    main: ListTeamsCurrent.hs
    source-dirs: Teams
    dependencies:
      - github-samples
  github-teaminfo-fir:
    main: TeamInfoFor.hs
    source-dirs: Teams
    dependencies:
      - github-samples
